export const PROOF_MODE = {
  INDUCTION: "INDUCTION",
  DIRECT: "DIRECT"
}

export const PROOF_STEP_TYPE = {
  ASSERT: "ASSERT",
  ASSUME: "ASSUME",
  TAKE_ARBITRARY: "TAKE_ARBITRARY",
  CASE_ANALYSIS: "CASE_ANALYSIS",
  EQUALITY: "EQUALITY"
}

export const ASSERT_JUSTIFICATION_TYPE = {
  IMPLICATION: "LOGICAL_IMPLICATION",
  ASSUMPTION_CLOSURE: "ASSUMPTION_CLOSURE"
}

export const EQUALITY_JUSTIFICATION = {
  FUNCTION_DEFINITION: "FUNCTION_DEFINITION",
  INDUCTIVE_HYPOTHESIS: "INDUCTIVE_HYPOTHESIS",
  ARITHMETIC: "ARITHMETIC"
}

