export const PROOF_MODE = {
  INDUCTION: "INDUCTION",
  DIRECT: "DIRECT"
}

export const PROOF_STEP_TYPE = {
  ASSERT: "ASSERT",
  ASSUME: "ASSUME",
  TAKE_ARBITRARY: "TAKE_ARBITRARY",
  CASE_ANALYSIS: "CASE_ANALYSIS"
}

export const ASSERT_JUSTIFICATION_TYPE = {
  IMPLICATION: "LOGICAL_IMPLICATION"
}

